name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sources
      run: sudo apt install libgtest-dev
    - name: Compile gtest sources
      run: sudo apt-get install cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls bin -al && sudo cp *.a /usr/lib
    - name: install editline
      run: sudo apt install libedit-dev
    - name: make
      run: make
    - name: make test
      run: make test
